/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Donor {
    age: bigint;
    weight: bigint;
    principal: Principal;
    bloodType: string;
    isEligible: boolean;
    name: string;
    healthStatus: string;
    location: string;
}
export type Time = bigint;
export interface Statistics {
    bloodStockLevels: Array<[string, bigint]>;
    totalDonations: bigint;
    emergencyRequests: bigint;
    totalDonors: bigint;
}
export interface EmergencyRequest {
    id: bigint;
    status: string;
    urgencyLevel: string;
    requester: Principal;
    bloodType: string;
    patientName: string;
    requestDate: Time;
    location: string;
}
export interface Notification {
    id: bigint;
    recipient: Principal;
    isRead: boolean;
    message: string;
    timestamp: Time;
}
export interface DonationRecord {
    id: bigint;
    bloodType: string;
    date: Time;
    quantity: bigint;
    donor: Principal;
    location: string;
}
export interface Appointment {
    id: bigint;
    status: string;
    donor: Principal;
    location: string;
    timeSlot: Time;
}
export interface UserProfile {
    age: bigint;
    weight?: bigint;
    contact: string;
    name: string;
    role: string;
    healthStatus?: string;
    bloodGroup: string;
    location: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBloodType(bloodType: string, initialQuantity: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookAppointment(timeSlot: Time, location: string): Promise<bigint>;
    cancelAppointment(appointmentId: bigint): Promise<void>;
    checkDonorEligibility(principal: Principal): Promise<boolean>;
    decreaseBloodQuantity(bloodType: string, amount: bigint): Promise<void>;
    getAllBloodInventory(): Promise<Array<[string, bigint]>>;
    getAllDonations(): Promise<Array<DonationRecord>>;
    getAppointments(): Promise<Array<Appointment>>;
    getBloodQuantity(bloodType: string): Promise<bigint>;
    getBloodStockLevels(): Promise<Array<[string, bigint]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDonationHistory(donor: Principal): Promise<Array<DonationRecord>>;
    getDonor(principal: Principal): Promise<Donor>;
    getEmergencyRequestCount(): Promise<bigint>;
    getEmergencyRequests(): Promise<Array<EmergencyRequest>>;
    getMyAppointments(): Promise<Array<Appointment>>;
    getMyEmergencyRequests(): Promise<Array<EmergencyRequest>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getPendingEmergencyRequests(): Promise<Array<EmergencyRequest>>;
    getStatistics(): Promise<Statistics>;
    getTotalDonors(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    increaseBloodQuantity(bloodType: string, amount: bigint): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    recordDonation(bloodType: string, quantity: bigint, location: string): Promise<bigint>;
    registerDonor(name: string, age: bigint, bloodType: string, location: string, weight: bigint, healthStatus: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchBloodByType(bloodType: string): Promise<bigint>;
    searchDonorsByBloodType(bloodType: string): Promise<Array<Donor>>;
    searchDonorsByLocation(location: string): Promise<Array<Donor>>;
    sendNotification(recipient: Principal, message: string): Promise<void>;
    submitEmergencyRequest(patientName: string, bloodType: string, location: string, urgencyLevel: string): Promise<bigint>;
    updateBloodQuantity(bloodType: string, quantity: bigint): Promise<void>;
    updateRequestStatus(requestId: bigint, status: string): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBloodType(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBloodType(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBloodType(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: Time, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0, arg1);
            return result;
        }
    }
    async cancelAppointment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async checkDonorEligibility(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkDonorEligibility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkDonorEligibility(arg0);
            return result;
        }
    }
    async decreaseBloodQuantity(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.decreaseBloodQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.decreaseBloodQuantity(arg0, arg1);
            return result;
        }
    }
    async getAllBloodInventory(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBloodInventory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBloodInventory();
            return result;
        }
    }
    async getAllDonations(): Promise<Array<DonationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDonations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDonations();
            return result;
        }
    }
    async getAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments();
            return result;
        }
    }
    async getBloodQuantity(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBloodQuantity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBloodQuantity(arg0);
            return result;
        }
    }
    async getBloodStockLevels(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBloodStockLevels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBloodStockLevels();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationHistory(arg0: Principal): Promise<Array<DonationRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationHistory(arg0);
            return result;
        }
    }
    async getDonor(arg0: Principal): Promise<Donor> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonor(arg0);
            return result;
        }
    }
    async getEmergencyRequestCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyRequestCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyRequestCount();
            return result;
        }
    }
    async getEmergencyRequests(): Promise<Array<EmergencyRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyRequests();
            return result;
        }
    }
    async getMyAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAppointments();
            return result;
        }
    }
    async getMyEmergencyRequests(): Promise<Array<EmergencyRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEmergencyRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEmergencyRequests();
            return result;
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return result;
        }
    }
    async getPendingEmergencyRequests(): Promise<Array<EmergencyRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingEmergencyRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingEmergencyRequests();
            return result;
        }
    }
    async getStatistics(): Promise<Statistics> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatistics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatistics();
            return result;
        }
    }
    async getTotalDonors(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalDonors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalDonors();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async increaseBloodQuantity(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.increaseBloodQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.increaseBloodQuantity(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async recordDonation(arg0: string, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDonation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDonation(arg0, arg1, arg2);
            return result;
        }
    }
    async registerDonor(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDonor(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDonor(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchBloodByType(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.searchBloodByType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchBloodByType(arg0);
            return result;
        }
    }
    async searchDonorsByBloodType(arg0: string): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDonorsByBloodType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDonorsByBloodType(arg0);
            return result;
        }
    }
    async searchDonorsByLocation(arg0: string): Promise<Array<Donor>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDonorsByLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDonorsByLocation(arg0);
            return result;
        }
    }
    async sendNotification(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendNotification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendNotification(arg0, arg1);
            return result;
        }
    }
    async submitEmergencyRequest(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitEmergencyRequest(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitEmergencyRequest(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateBloodQuantity(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBloodQuantity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBloodQuantity(arg0, arg1);
            return result;
        }
    }
    async updateRequestStatus(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRequestStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRequestStatus(arg0, arg1);
            return result;
        }
    }
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight: [] | [bigint];
    contact: string;
    name: string;
    role: string;
    healthStatus: [] | [string];
    bloodGroup: string;
    location: string;
}): {
    age: bigint;
    weight?: bigint;
    contact: string;
    name: string;
    role: string;
    healthStatus?: string;
    bloodGroup: string;
    location: string;
} {
    return {
        age: value.age,
        weight: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.weight)),
        contact: value.contact,
        name: value.name,
        role: value.role,
        healthStatus: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.healthStatus)),
        bloodGroup: value.bloodGroup,
        location: value.location
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight?: bigint;
    contact: string;
    name: string;
    role: string;
    healthStatus?: string;
    bloodGroup: string;
    location: string;
}): {
    age: bigint;
    weight: [] | [bigint];
    contact: string;
    name: string;
    role: string;
    healthStatus: [] | [string];
    bloodGroup: string;
    location: string;
} {
    return {
        age: value.age,
        weight: value.weight ? candid_some(value.weight) : candid_none(),
        contact: value.contact,
        name: value.name,
        role: value.role,
        healthStatus: value.healthStatus ? candid_some(value.healthStatus) : candid_none(),
        bloodGroup: value.bloodGroup,
        location: value.location
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
