 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : string,
  'donor' : Principal,
  'location' : string,
  'timeSlot' : Time,
}
export interface DonationRecord {
  'id' : bigint,
  'bloodType' : string,
  'date' : Time,
  'quantity' : bigint,
  'donor' : Principal,
  'location' : string,
}
export interface Donor {
  'age' : bigint,
  'weight' : bigint,
  'principal' : Principal,
  'bloodType' : string,
  'isEligible' : boolean,
  'name' : string,
  'healthStatus' : string,
  'location' : string,
}
export interface EmergencyRequest {
  'id' : bigint,
  'status' : string,
  'urgencyLevel' : string,
  'requester' : Principal,
  'bloodType' : string,
  'patientName' : string,
  'requestDate' : Time,
  'location' : string,
}
export interface Notification {
  'id' : bigint,
  'recipient' : Principal,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export interface Statistics {
  'bloodStockLevels' : Array<[string, bigint]>,
  'totalDonations' : bigint,
  'emergencyRequests' : bigint,
  'totalDonors' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'weight' : [] | [bigint],
  'contact' : string,
  'name' : string,
  'role' : string,
  'healthStatus' : [] | [string],
  'bloodGroup' : string,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBloodType' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[Time, string], bigint>,
  'cancelAppointment' : ActorMethod<[bigint], undefined>,
  'checkDonorEligibility' : ActorMethod<[Principal], boolean>,
  'decreaseBloodQuantity' : ActorMethod<[string, bigint], undefined>,
  'getAllBloodInventory' : ActorMethod<[], Array<[string, bigint]>>,
  'getAllDonations' : ActorMethod<[], Array<DonationRecord>>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getBloodQuantity' : ActorMethod<[string], bigint>,
  'getBloodStockLevels' : ActorMethod<[], Array<[string, bigint]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDonationHistory' : ActorMethod<[Principal], Array<DonationRecord>>,
  'getDonor' : ActorMethod<[Principal], Donor>,
  'getEmergencyRequestCount' : ActorMethod<[], bigint>,
  'getEmergencyRequests' : ActorMethod<[], Array<EmergencyRequest>>,
  'getMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'getMyEmergencyRequests' : ActorMethod<[], Array<EmergencyRequest>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getPendingEmergencyRequests' : ActorMethod<[], Array<EmergencyRequest>>,
  'getStatistics' : ActorMethod<[], Statistics>,
  'getTotalDonors' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'increaseBloodQuantity' : ActorMethod<[string, bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'recordDonation' : ActorMethod<[string, bigint, string], bigint>,
  'registerDonor' : ActorMethod<
    [string, bigint, string, string, bigint, string],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchBloodByType' : ActorMethod<[string], bigint>,
  'searchDonorsByBloodType' : ActorMethod<[string], Array<Donor>>,
  'searchDonorsByLocation' : ActorMethod<[string], Array<Donor>>,
  'sendNotification' : ActorMethod<[Principal, string], undefined>,
  'submitEmergencyRequest' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'updateBloodQuantity' : ActorMethod<[string, bigint], undefined>,
  'updateRequestStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];