 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const DonationRecord = IDL.Record({
  'id' : IDL.Nat,
  'bloodType' : IDL.Text,
  'date' : Time,
  'quantity' : IDL.Nat,
  'donor' : IDL.Principal,
  'location' : IDL.Text,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'donor' : IDL.Principal,
  'location' : IDL.Text,
  'timeSlot' : Time,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Nat),
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'healthStatus' : IDL.Opt(IDL.Text),
  'bloodGroup' : IDL.Text,
  'location' : IDL.Text,
});
export const Donor = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Nat,
  'principal' : IDL.Principal,
  'bloodType' : IDL.Text,
  'isEligible' : IDL.Bool,
  'name' : IDL.Text,
  'healthStatus' : IDL.Text,
  'location' : IDL.Text,
});
export const EmergencyRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'urgencyLevel' : IDL.Text,
  'requester' : IDL.Principal,
  'bloodType' : IDL.Text,
  'patientName' : IDL.Text,
  'requestDate' : Time,
  'location' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'recipient' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Statistics = IDL.Record({
  'bloodStockLevels' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalDonations' : IDL.Nat,
  'emergencyRequests' : IDL.Nat,
  'totalDonors' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBloodType' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func([Time, IDL.Text], [IDL.Nat], []),
  'cancelAppointment' : IDL.Func([IDL.Nat], [], []),
  'checkDonorEligibility' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'decreaseBloodQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllBloodInventory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAllDonations' : IDL.Func([], [IDL.Vec(DonationRecord)], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getBloodQuantity' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getBloodStockLevels' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonationHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DonationRecord)],
      ['query'],
    ),
  'getDonor' : IDL.Func([IDL.Principal], [Donor], ['query']),
  'getEmergencyRequestCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getEmergencyRequests' : IDL.Func([], [IDL.Vec(EmergencyRequest)], ['query']),
  'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getMyEmergencyRequests' : IDL.Func(
      [],
      [IDL.Vec(EmergencyRequest)],
      ['query'],
    ),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPendingEmergencyRequests' : IDL.Func(
      [],
      [IDL.Vec(EmergencyRequest)],
      ['query'],
    ),
  'getStatistics' : IDL.Func([], [Statistics], ['query']),
  'getTotalDonors' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'increaseBloodQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'recordDonation' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'registerDonor' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchBloodByType' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'searchDonorsByBloodType' : IDL.Func([IDL.Text], [IDL.Vec(Donor)], ['query']),
  'searchDonorsByLocation' : IDL.Func([IDL.Text], [IDL.Vec(Donor)], ['query']),
  'sendNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'submitEmergencyRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateBloodQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateRequestStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const DonationRecord = IDL.Record({
    'id' : IDL.Nat,
    'bloodType' : IDL.Text,
    'date' : Time,
    'quantity' : IDL.Nat,
    'donor' : IDL.Principal,
    'location' : IDL.Text,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'donor' : IDL.Principal,
    'location' : IDL.Text,
    'timeSlot' : Time,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Nat),
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'healthStatus' : IDL.Opt(IDL.Text),
    'bloodGroup' : IDL.Text,
    'location' : IDL.Text,
  });
  const Donor = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Nat,
    'principal' : IDL.Principal,
    'bloodType' : IDL.Text,
    'isEligible' : IDL.Bool,
    'name' : IDL.Text,
    'healthStatus' : IDL.Text,
    'location' : IDL.Text,
  });
  const EmergencyRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'urgencyLevel' : IDL.Text,
    'requester' : IDL.Principal,
    'bloodType' : IDL.Text,
    'patientName' : IDL.Text,
    'requestDate' : Time,
    'location' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'recipient' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Statistics = IDL.Record({
    'bloodStockLevels' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalDonations' : IDL.Nat,
    'emergencyRequests' : IDL.Nat,
    'totalDonors' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBloodType' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func([Time, IDL.Text], [IDL.Nat], []),
    'cancelAppointment' : IDL.Func([IDL.Nat], [], []),
    'checkDonorEligibility' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'decreaseBloodQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllBloodInventory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAllDonations' : IDL.Func([], [IDL.Vec(DonationRecord)], ['query']),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getBloodQuantity' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getBloodStockLevels' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonationHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DonationRecord)],
        ['query'],
      ),
    'getDonor' : IDL.Func([IDL.Principal], [Donor], ['query']),
    'getEmergencyRequestCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getEmergencyRequests' : IDL.Func(
        [],
        [IDL.Vec(EmergencyRequest)],
        ['query'],
      ),
    'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getMyEmergencyRequests' : IDL.Func(
        [],
        [IDL.Vec(EmergencyRequest)],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPendingEmergencyRequests' : IDL.Func(
        [],
        [IDL.Vec(EmergencyRequest)],
        ['query'],
      ),
    'getStatistics' : IDL.Func([], [Statistics], ['query']),
    'getTotalDonors' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'increaseBloodQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'recordDonation' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'registerDonor' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchBloodByType' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'searchDonorsByBloodType' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Donor)],
        ['query'],
      ),
    'searchDonorsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Donor)],
        ['query'],
      ),
    'sendNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'submitEmergencyRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateBloodQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateRequestStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };